// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcfAyXiTjG1k33YJ88qHPlaB-EAqqxfq0',
    appId: '1:581281660711:web:d32a83b971d9938b327302',
    messagingSenderId: '581281660711',
    projectId: 'mbrm-68790',
    authDomain: 'mbrm-68790.firebaseapp.com',
    storageBucket: 'mbrm-68790.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dtncOgK445mJ2H8Zdym1qfovzpIAs-g',
    appId: '1:581281660711:android:16b25a122a7063fd327302',
    messagingSenderId: '581281660711',
    projectId: 'mbrm-68790',
    storageBucket: 'mbrm-68790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJNYJrjed6dbiZEXpFWRwcJxcbmxAdlEk',
    appId: '1:581281660711:ios:4656db8766504446327302',
    messagingSenderId: '581281660711',
    projectId: 'mbrm-68790',
    storageBucket: 'mbrm-68790.appspot.com',
    iosClientId: '581281660711-3a2er7fmic3kh3791pcgsmag2takn9d1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mbr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJNYJrjed6dbiZEXpFWRwcJxcbmxAdlEk',
    appId: '1:581281660711:ios:76463a7ae34118a3327302',
    messagingSenderId: '581281660711',
    projectId: 'mbrm-68790',
    storageBucket: 'mbrm-68790.appspot.com',
    iosClientId: '581281660711-a2beip3k00huqj3t056n0jqoomdo0o1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.mbr.RunnerTests',
  );
}
